### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by jiuqinyan** [mochat-cloud/mochat-java#17]
## 我用的环境

* Java 版本：1.8
* MoChat 版本：master
* MySQL 版本：5.7

## 问题及现象
![image](https://user-images.githubusercontent.com/43592290/122179385-0b138680-ceba-11eb-9ef4-ad5edfa2075a.png)
![image](https://user-images.githubusercontent.com/43592290/122179435-1961a280-ceba-11eb-9dd7-3cad8ce24a85.png)
初始化无数据直接空指针，建议替换成  CollectionUtils.isEmpty()形式

**Comment by YpwCode** [comment]
您好，您反馈的问题已修复，请拉取最新代码进行确认
