### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by Zengt123456** [mochat-cloud/mochat-java#22]
## 我用的环境

* Java 版本：
* MoChat 版本：
* MySQL 版本：

## 问题及现象

![image](https://user-images.githubusercontent.com/72057413/123360486-fca32a00-d59f-11eb-9bb2-2d451961de4a.png)

![image](https://user-images.githubusercontent.com/72057413/123360501-0331a180-d5a0-11eb-9a6d-e445fa58bf66.png)
部分接口权限（如上图下拉列表），权限里面没有提供配置。

**Comment by YpwCode** [comment]
感谢您的反馈，您提供的这个问题在项目设计的时候没有考虑在权限配置内，如有需要您可以 fork 本项目，自行扩展和自定义符合您的方案。谢谢
