### ISSUE TITLE
tolistType值的问题

### ISSUE THREAD

**Issue by jiuqinyan** [mochat-cloud/mochat-java#25]
## 我用的环境

* Java 版本：
* MoChat 版本：
* MySQL 版本：

## 问题及现象

![image](https://user-images.githubusercontent.com/43592290/123760483-76fee180-d8f3-11eb-955d-9c4decc2d6b4.png)
当from是外部联系人，to是企微用户的时候被归为toType被归为0
![image](https://user-images.githubusercontent.com/43592290/123761437-6733cd00-d8f4-11eb-993c-e24397a6de42.png)
只能查到单方面的对话记录
tolistType的值是否要重新定义

**Comment by YpwCode** [comment]
非常感谢您的反馈，下面是对您疑问的回答：
- 根据企业微信 API 里提供的文档，toType 的判断依据是以”wo”或”wm”开头为“外部联系人”（客户），理论上不会出现问题。
- tolistType 属于冗余字段属于设计缺陷，不影响项目运行。
希望能对您有所帮助，谢谢
